@endpoint = https://rkxsphe8va.execute-api.eu-west-2.amazonaws.com/prod
GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces?spaceId=1662379459972
###

GET {{endpoint}}/spaces

###
POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "London",
    "name": "Best location"
}
###