@endpoint = https://rkxsphe8va.execute-api.eu-west-2.amazonaws.com/prod

GET {{endpoint}}/spaces
###

GET {{endpoint}}/spaces?location=London
###

GET {{endpoint}}/spaces?spaceId=1662386442547
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "London",
    "name": "Best location"
}
###

PUT {{endpoint}}/spaces?spaceId=1662386463852
Content-Type: application/json

{
    "location": "Updated location"
}
###

DELETE {{endpoint}}/spaces?spaceId=1662386442547
Content-Type: application/json
###